### PR TITLE
Improve license texts translations

### PR DESCRIPTION
**Pull request by cyb3rko**
I aligned all the licenses to have the exact same syntax.
I wrapped them all to the exact length of the horizontal lines.
And the links for the licensors and licensees were not well indented.

In the English licenses there were also some underscores which don't make any sense.

In the German README I removed the english names of the licenses in brackets to be exact the same as the Spanish and English README.

**I think now the translations should be PERFECT.**

### CODE REVIEW

**Comment by santisoler** [comment]
Hi @cyb3rko! Thanks for doing this. I agree with the corrections to the German README and the line fix on the Spanish one.
The German license text had this long dashes (probably due to the copy-paste from the website), so it's better to replace them for regular dashes `-`.

Regarding the English text, I think we should keep the original text as it is. Creative Commons provide the text, so it's better to keep the same license file. In fact, that way we may check if we are hosting the same version through checksums.
BTW, although not the translations are being hosted by CC, I think we could remove those text files from our repository and make the links point their files, but I'll leave this for a different PR.

So, try to restore the English license texts to their original versions and then we can merge this.

**Comment by cyb3rko** [comment]
Where do you still see the long dashes? I thought I replaced them all in the last commits.

If you want to remove the english license text I would suppose that we don't have to change anything there anymore?

**Comment by santisoler** [comment]
> Where do you still see the long dashes? I thought I replaced them all in the last commits.

Sorry if I haven't expressed myself very well. I was talking about the dashes you actually replaced, I was just saying that I agree to do so.

> If you want to remove the english license text I would suppose that we don't have to change anything there anymore?

Yes and no. Although we _might_ remove them on a future PR, it's better not to include random changes on PRs. So even if we are considering to remove them, it's better to keep them the same as the original for now. A good practice of software versioning is tackling down one (or few very related) issues on each PR, independently of decisions that are being thought at the same time.
So I would restore them to the original ones, then merge this PR, and then opening a new one for removing them, i.e. fixing #9 on a different PR.

**Comment by cyb3rko** [comment]
Ok, if you think so I of course do that.

But I don't really understand why the original licenses aren't wrapped to the length of those horizontal lines like we did in our translated licenses, doesn't make sense to me. But it's their choice...

**Comment by cyb3rko** [comment]
Oops

**Comment by cyb3rko** [comment]
Did the last commit fix it?
I think it should be fine now

**Pull request merged**
