### PR TITLE
Add CC-BY-NC-SA license

### PR DESCRIPTION
**Pull request by weensy**
Add CC BY-NC-SA License plain text to repository. Add instructions for adding
the license notice for CC BY-NC-SA to the `README.md`.

### CODE REVIEW

**Comment by santisoler** [comment]
Thanks @vaporwavy for opening the PR! It's very welcomed!

Could you expand the `README.md` to include this license? We would need to add it to the list of licenses and create a subsection with the Markdown code to add it to any other `README.md` (as we have for CC-BY and CC-BY-SA).
If you don't have the time or don't feel that you could do that, no problem, just let me know!

Thanks again for the contribution! 🙌🏼

**Comment by weensy** [comment]
Okay, I'll take it!
I will make a new PR soon. :)

**Comment by weensy** [comment]
I have updated a CC BY-NC-SA 4.0 section on `README.md`!

**Review by santisoler — CHANGES_REQUESTED** [review]
Great work @vaporwavy! Thanks adding the changes to the `README.md`!

I think you should rename the licence file to `LICENSE-CC-BY-NC-SA` so it follows the same style as the other ones (besides, the link to the license file present in the `README.md` is broken because of that).
Besides that, this is ready to be merged. 🏅

**Comment by weensy** [comment]
Oh, thank you for finding the naming mistake. It has been renamed now!

**Comment by santisoler** [comment]
Thanks @vaporwavy for the contribution! I'm merging this PR! 🏅 🚀

**Review by santisoler — APPROVED** [review]

**Pull request merged**
