### PR TITLE
Add Spanish translation of license texts

### LINKED ISSUE #3: Add Spanish translation
After #2 opened by @cyb3rko, I think would be nice to add a Spanish translation of the CC Licenses and the `README.md`.
We can wait until #2 is merged, but my idea so far is having one directory for each translation. Like:

```
de
 ├── LICENSE-CC-BY
 ├── LICENSE-CC-BY-SA
 └── README.md 
es
 ├── LICENSE-CC-BY
 ├── LICENSE-CC-BY-SA
 └── README.md 
LICENSE-CC-BY
LICENSE-CC-BY-SA
README.md 
```

We should check if GitHub automatically recognizes the license out of a translated `LICENSE` file. If not, we should add a note encouraging people to add both the English and the translated version of the license text.

### PR DESCRIPTION
**Pull request by cyb3rko**
Fixes #3.

I finished converting the Spanish translations of the licenses and I already added the badge for Spanish.
The README has to do someone else.

I hope this time I did it the right way...

### CODE REVIEW

**Comment by santisoler** [comment]
Thanks again @cyb3rko.

I'm curious, where did you find the translated plain text version of the license?
Does Creative Commons serves it as they serve the [English version](https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt)?
Or did you copied the text in https://creativecommons.org/licenses/by-sa/4.0/legalcode.es and reformatted it?

**Comment by cyb3rko** [comment]
Where have you found the link to the formatted English version??

I just reformatted the text from here https://creativecommons.org/licenses/by-sa/4.0/legalcode.es into plain text.

Have I done everything correct with the fork etc.?

**Comment by santisoler** [comment]
> Where have you found the link to the formatted English version??

I found this blog entry: https://creativecommons.org/2014/01/07/plaintext-versions-of-creative-commons-4-0-licenses/

> I just reformatted the text from here https://creativecommons.org/licenses/by-sa/4.0/legalcode.es into plain text.

I imagined... Maybe would be nice to reach them out so they can make all license texts available in plain text.
It would be much better if our links just point to Creative Commons files rather than hosting our own (which by the way may not get updates or typo fixes). 

> Have I done everything correct with the fork etc.?

Yes! Now the PR is opened from your `spanish` branch. Congrats!

**Comment by cyb3rko** [comment]
> I found this blog entry: https://creativecommons.org/2014/01/07/plaintext-versions-of-creative-commons-4-0-licenses/

Oh, I see.

> ... 
> Maybe would be nice to reach them out so they can make all license texts available in plain text.
> It would be much better if our links just point to Creative Commons files rather than hosting our own (which by the way may not get updates or typo fixes).

Maybe this is a good idea, do you wanna contact them?

> Yes! Now the PR is opened from your `spanish` branch. Congrats!

Nice, finally.

**Comment by santisoler** [comment]
Ok, I just opened an Issue to contact them: https://github.com/creativecommons/creativecommons.org/issues/1130

**Comment by cyb3rko** [comment]
I think the response will be late or never come, so maybe we should include our versions first and then, if someday they publish official plain texts, we can replace ours in the future, right?

**Comment by santisoler** [comment]
Sure! We don't need to wait for the plain text to be available at their repo. In fact, it's very likely we might need to tackle down that issue that I opened on their repository. So having some translations already in plain text is just working in advance.

Although, the translations are too many to do it manually. I'll check if there's a way to convert them automatically. I'm thinking of using `pandoc` to convert it to Markdown, and then doing some minor text formatting... any ideas are welcome!

**Comment by santisoler** [comment]
This PR is ready to be merged. I'll wait until #6 is ready, and then merge both together.

Thanks again for taking the effort of formatting the HTML versions!

**Comment by cyb3rko** [comment]
I use Visual Studio Code to automatically wrap the licenses to colum 72, so this makes it a lot easier to format.
I can copy the texts, adjust the indents etc. and then I'm already finished.

I never used `pandoc` and it seems like it could be used for it but I have no experience until now...

**Pull request merged**
